import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/theme';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, backgroundColor: Colors.white, borderBottomWidth: 1, borderBottomColor: Colors.border },
  topBarBtn: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  topTitle: { fontSize: 18, fontWeight: '700', color: Colors.navy },
  tabBarWrap: { backgroundColor: Colors.white, borderBottomWidth: 1, borderBottomColor: Colors.border },
  tabBarScroll: { paddingHorizontal: 12, paddingVertical: 8, gap: 6 },
  tabPill: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, backgroundColor: Colors.bg, gap: 6 },
  tabPillActive: { backgroundColor: Colors.navy },
  tabPillLabel: { fontSize: 13, fontWeight: '500', color: Colors.textSec },
  tabPillLabelActive: { color: Colors.white, fontWeight: '600' },
  content: { padding: 16, paddingBottom: 24 },
  secTitle: { fontSize: 20, fontWeight: '700', color: Colors.navy, marginBottom: 16 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', marginHorizontal: -5 },
  statCard: { width: '50%', padding: 5 },
  statCardInner: { backgroundColor: Colors.white, borderRadius: 14, padding: 16, alignItems: 'center', borderWidth: 1, borderColor: Colors.border },
  statIcon: { width: 52, height: 52, borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  statVal: { fontSize: 32, fontWeight: '800', color: Colors.textMain, marginBottom: 2 },
  statLabel: { fontSize: 13, fontWeight: '500', color: Colors.textMuted },
  quickGrid: { flexDirection: 'row', flexWrap: 'wrap', marginHorizontal: -5 },
  quickAction: { width: '50%', padding: 5 },
  quickActionIcon: { width: 44, height: 44, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  quickActionLabel: { fontSize: 13, fontWeight: '600', color: Colors.textMain },
  listCard: { backgroundColor: Colors.white, borderRadius: 12, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: Colors.border },
  listRow: { flexDirection: 'row', alignItems: 'center' },
  iconCircle: { width: 38, height: 38, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  listTitle: { fontSize: 15, fontWeight: '600', color: Colors.textMain, marginBottom: 2 },
  listSub2: { fontSize: 13, color: Colors.textSec, marginBottom: 2 },
  listMeta: { fontSize: 12, color: Colors.textMuted },
  emptyText: { textAlign: 'center', color: Colors.textMuted, marginTop: 40, fontSize: 15 },
  addBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.navy, margin: 16, marginBottom: 0, padding: 14, borderRadius: 12 },
  addBtnText: { fontSize: 15, fontWeight: '600', color: Colors.white, marginLeft: 8 },
  statusDot: { width: 10, height: 10, borderRadius: 5 },
  assocSection: { marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: Colors.border, marginLeft: 50 },
  assocTitle: { fontSize: 12, fontWeight: '600', color: Colors.textMuted, marginBottom: 6 },
  assocRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6 },
  assocName: { fontSize: 13, fontWeight: '500', color: Colors.textMain },
  assocInfo: { fontSize: 11, color: Colors.textMuted, marginTop: 1 },
  notAbilitato: { flexDirection: 'row', alignItems: 'center', marginTop: 8, marginLeft: 50 },
  notAbilitatoText: { fontSize: 12, color: '#D97706', fontWeight: '500', marginLeft: 4 },
  assocBtn: { flexDirection: 'row', alignItems: 'center', marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: Colors.border, marginLeft: 50 },
  assocBtnText: { fontSize: 13, fontWeight: '600', color: Colors.sky, marginLeft: 6 },
  actionRow: { flexDirection: 'row', marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: Colors.border, gap: 8, marginLeft: 50 },
  miniBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, gap: 6 },
  miniBtnText: { fontSize: 13, fontWeight: '600' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  modal: { backgroundColor: Colors.white, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, maxHeight: '85%' },
  modalTitle: { fontSize: 20, fontWeight: '700', color: Colors.navy, marginBottom: 8 },
  modalSub: { fontSize: 15, color: Colors.textSec, marginBottom: 4 },
  modalDesc: { fontSize: 14, color: Colors.textSec, marginBottom: 16, lineHeight: 20 },
  modalLabel: { fontSize: 14, fontWeight: '600', color: Colors.textMain, marginBottom: 8 },
  statusBtn: { padding: 14, borderRadius: 10, borderWidth: 1, borderColor: Colors.border, marginBottom: 8 },
  statusBtnText: { fontSize: 15, color: Colors.textMain, textAlign: 'center', fontWeight: '500' },
  closeBtn: { padding: 14, alignItems: 'center', marginTop: 4 },
  closeBtnText: { fontSize: 15, color: Colors.textMuted, fontWeight: '500' },
  input: { height: 52, borderRadius: 10, borderWidth: 1, borderColor: Colors.border, paddingHorizontal: 16, fontSize: 16, color: Colors.textMain, marginBottom: 12, backgroundColor: Colors.bg },
  inputGroup: { marginBottom: 4 },
  inputLabel: { fontSize: 14, fontWeight: '500', color: Colors.textSec, marginBottom: 6 },
  configSection: { backgroundColor: Colors.white, borderRadius: 14, padding: 18, marginBottom: 16, borderWidth: 1, borderColor: Colors.border },
  configSectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 14, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: Colors.border },
  configSectionTitle: { fontSize: 16, fontWeight: '600', color: Colors.navy, marginLeft: 10 },
  configField: { marginBottom: 6 },
  configLabel: { fontSize: 13, fontWeight: '500', color: Colors.textSec, marginBottom: 4 },
  configHint: { fontSize: 13, color: Colors.textSec, marginBottom: 12 },
  exportBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.skyLight, borderRadius: 10, padding: 14, marginBottom: 8 },
  exportBtnText: { fontSize: 14, fontWeight: '600', color: Colors.navy, marginLeft: 10 },
  ecUserBtn: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.border },
  ecUserName: { fontSize: 14, fontWeight: '600', color: Colors.textMain },
  ecUserCond: { fontSize: 12, color: Colors.textMuted, marginTop: 1 },
  attachRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: Colors.border },
  attachThumb: { width: 44, height: 44, borderRadius: 8, backgroundColor: Colors.bg },
  attachIcon: { width: 44, height: 44, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  mediaSection: { marginTop: 8, marginBottom: 16 },
  mediaSectionTitle: { fontSize: 15, fontWeight: '600', color: Colors.textMain, marginBottom: 4 },
  mediaSectionHint: { fontSize: 12, color: Colors.textMuted, marginBottom: 14 },
  mediaButtons: { flexDirection: 'row', gap: 10 },
  mediaBtn: { flex: 1, alignItems: 'center', backgroundColor: Colors.white, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: Colors.border },
  mediaBtnIcon: { width: 46, height: 46, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  mediaBtnLabel: { fontSize: 12, fontWeight: '600', color: Colors.textSec },
  filesList: { marginTop: 14 },
  filesCount: { fontSize: 12, fontWeight: '600', color: Colors.textMuted, marginBottom: 8 },
  fileItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: 10, padding: 10, marginBottom: 8, borderWidth: 1, borderColor: Colors.border },
  fileThumbnail: { width: 48, height: 48, borderRadius: 8, backgroundColor: Colors.bg },
  fileIconWrap: { width: 48, height: 48, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  fileInfo: { flex: 1, marginLeft: 12 },
  fileName: { fontSize: 13, fontWeight: '600', color: Colors.textMain },
  fileMetaRow: { flexDirection: 'row', alignItems: 'center', marginTop: 2 },
  fileMeta: { fontSize: 11, color: Colors.textMuted },
  removeBtn: { padding: 4 },
  progressBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.skyLight, borderRadius: 10, padding: 12, marginBottom: 12, gap: 8 },
  progressText: { fontSize: 13, fontWeight: '500', color: Colors.navy },
  badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  submitBtn: { backgroundColor: Colors.navy, borderRadius: 12, padding: 16, alignItems: 'center', marginTop: 8 },
  submitBtnText: { fontSize: 16, fontWeight: '700', color: Colors.white },
});

export const cs2 = StyleSheet.create({
  pill: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.bg, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, borderWidth: 1, borderColor: Colors.border, gap: 4 },
  pillText: { fontSize: 12, color: Colors.textSec, fontWeight: '500' },
  metaText: { fontSize: 12, color: Colors.textSec },
});

export const pvs = StyleSheet.create({
  alertBanner: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: '#FEE2E2',
    borderRadius: 10, padding: 12, marginBottom: 14, borderLeftWidth: 3, borderLeftColor: '#DC2626',
  },
  alertText: { fontSize: 13, color: '#DC2626', fontWeight: '600', flex: 1, marginLeft: 8 },
  alertBtn: { backgroundColor: '#DC2626', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  alertBtnText: { fontSize: 12, fontWeight: '600', color: '#FFFFFF' },
  filterLabel: { fontSize: 12, fontWeight: '700', color: Colors.textSec, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 },
  chip: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1, borderColor: Colors.border, backgroundColor: Colors.white },
  chipActive: { backgroundColor: Colors.navy, borderColor: Colors.navy },
  chipText: { fontSize: 13, color: Colors.textSec, fontWeight: '500' },
  chipTextActive: { color: Colors.white },
  emptyBox: { alignItems: 'center', paddingVertical: 48 },
  emptyText: { fontSize: 16, fontWeight: '600', color: Colors.textSec, marginTop: 12 },
  emptySubText: { fontSize: 13, color: Colors.textMuted, marginTop: 4 },
  card: {
    backgroundColor: Colors.white, borderRadius: 12, padding: 14, marginBottom: 10,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2,
  },
  cardScadente: { borderLeftWidth: 3, borderLeftColor: '#DC2626' },
  cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  cardRow: { flexDirection: 'row', alignItems: 'flex-start' },
  tipoBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  tipoBadgeText: { fontSize: 12, fontWeight: '600', color: Colors.navy },
  statoBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  statoBadgeText: { fontSize: 12, fontWeight: '600', textTransform: 'capitalize' },
  cardNome: { fontSize: 14, fontWeight: '600', color: Colors.textMain },
  cardProto: { fontSize: 12, color: Colors.sky, fontWeight: '500', marginTop: 1 },
  cardDate: { fontSize: 12, color: Colors.textSec, marginTop: 2 },
  scadBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.bg, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8, gap: 3 },
  scadBadgeRed: { backgroundColor: '#FEE2E2' },
  scadText: { fontSize: 12, color: Colors.textSec, fontWeight: '500' },
  scadTextRed: { color: '#DC2626', fontWeight: '700' },
});
